phac-nml/ncov2019-artic-nf

conf/coguk.config, conf/coguk/nml.config
Actually create the PR to the right location...
Adds initial config to test off of and see what improvements need to be made from it
=> Add Initial NML Config

conf/base.config, conf/nanopore.config
Changed min and max read length filtering to match
=> Switch to resend primer scheme.

bin/irida_samples.py, conf/base.config, conf/conda.config, environments/irida_uploader.yml, modules/nml.nf, workflows/articNcovNanopore.nf
Some things to potentially think about:
- `ln` vs `mv` for the files
- See if I can find a way to use ln, currently it won't work as its making a sym link of a sym link
- ~~Don't think I need the path to irida upload in the generateIridaReport process~~ -> Used for error checking
- ~~I can probably delete base_dir from my python script as I removed those code lines to get it to work with nextflow~~
- Changing process names and input names if needed
- Creation of the uploadIrida process
- Merging of current workflow to ours
=> Initial Irida Upload progress

bin/irida_samples.py, modules/nml.nf, workflows/articNcovNanopore.nf
Restructured the SampleList creator and the movement of files to make it more streamlined
=> Restructure Irida Output

bin/irida_samples.py
having CT will make better qc plots in ncov-tools
=> add ct column to sample sheet

conf/coguk/nml.config
Partition off less resources for processes when they are not called for
=> More specific resource allocation

bin/qc.py
Added qc metrics:
- Total number of N's in the consensus sequence
- Coverage Depth
=> Add metrics to QC

bin/irida_samples.py
Small changes to python code when the sample is being renamed with `--fastq` input such that if its not in the samplesheet the file will still be detected
=> Small fix to renaming samples

bin/qc.py, modules/help.nf, modules/nml.nf, modules/qc.nf, workflows/articNcovNanopore.nf
Changed up some of the order of the code to allow lineage calls to be added to the final qc output
=> Add lineages calls to qc output

bin/qc.py, modules/qc.nf
Adding more info to qc.csv that will be important for irida upload
Also removing unneeded info from it (looking at you bam and fasta file names)
=> Add additional information to qc.csv

bin/qc.py, environments/extras.yml, modules/artic.nf, modules/qc.nf, workflows/articNcovNanopore.nf
Adding the variants found in minion nanopolish to the output results formatted as `ReferencePositionAlternate;`
=> Add variants to csv output

bin/irida_fasta.py, bin/irida_fastq.py
Allows the user to accidently have an extra tab in the samplesheet without the whole analysis being destroyed
Added a print statement of the problem area as well so that there is more info out if an error is occuring
=> Slightly less strict tsv input files

environments/ncovtools.yml
Add and set dependencies to fix allow ncov tools to run again
=> Update ncovtools env for pangolin update

environments/ncovtools.yml
I broke the current environment in the P drive and this change better represents what ncov-tools has as its environment along with being working and installed on the cluster
=> Update to ncovtools environment.yml file

conf/nanopore.config, extra_data/config.yaml, modules/nml.nf, workflows/articNcovNanopore.nf
- Added the nCoV.bed file to ncov-tools input
- Modified ncov-tools config file with new inputs
- Tested workflow
=> Update files and names for ncov-tools update

bin/qc.py
=> Change column name

bin/correct_n.py, bin/irida_fasta.py, bin/qc.py, conf/conda.config, conf/nanopore.config, environments/extras.yml, environments/irida_uploader.yml, extra_data/config.yaml, modules/artic.nf, modules/nml.nf, workflows/articNcovNanopore.nf
Double checks and corrects N's in fail vcf with python script and bcftools
Additional automation of uploading to IRIDA available
=> Double check Ns in fail.vcf

conf/conda.config
Fix wrong env given to correctN module
=> fix correctn environment

bin/irida_fast5.py, conf/coguk/nml.config
Its been taking 2 hours to compress these files, we don't like that :( so hopefully it goes faster now
=> More cores to pigz

bin/correct_n.py, modules/nml.nf, workflows/articNcovNanopore.nf
Rare occurrence of indels in the output from bcftools now skipped
Improved the correctN process as well to match the other similar ones by joining the inputs
=> Correct N fixes and pipeline improvements for it

bin/irida_fast5.py, conf/coguk/nml.config
Current version does not seem to work on our infrastructure so setting it back to what it was previously
=> Fix pigz as it was not working as intended

environments/ncovtools.yml
Small update to the ncov-tools environment
Bigger update with the 1.3 changes to come once it has been validated
=> update ncovtools env to match ncovtools 1.3

bin/run_ncovtools.sh, conf/conda.config, environments/snpdist.yml, modules/nml.nf, workflows/articNcovNanopore.nf
Pretty much just added the snp-dists tool to the ncov-tools aligned fasta output
Quick test on our data confirms that it did indeed run
=> Added new snpdist commands to generate matrix.tsv

.github/scripts/test_PR_against_release.sh, .github/scripts/test_cram_input.sh, .github/scripts/test_typing.sh, bin/qc.py, bin/type_vcf.py, conf/illumina.config, conf/nanopore.config, environments/illumina/Dockerfile, environments/illumina/Singularity, environments/illumina/environment.yml, environments/nanopore/Dockerfile, environments/nanopore/Singularity, modules/artic.nf, modules/help.nf, modules/illumina.nf, modules/qc.nf, modules/typing.nf, typing/MN908947.3.gff, typing/SARS-CoV-2.types.yaml, workflows/articNcovNanopore.nf, workflows/illuminaNcov.nf, workflows/typing.nf
Changes:
- Adding newly created typing modules into pipeline
- accessed with `--gff <gff_file>` and --yaml <specific yaml configuration>`
- more configurations to go with them
=> Update our fork with the latest upstream changes

bin/qc.py, modules/nml.nf, modules/qc.nf, workflows/articNcovNanopore.nf
Add the snpEFF AA table protein mutations that are generated by ncov-tools and the sequencing primer scheme used for the sample
=> Add snpeff output to qc

conf/coguk/nml.config
Adding retries to hopefully allow most runs to complete without issue
=> Add retries to pipeline

bin/qc.py, bin/run_ncovtools.sh, conf/nanopore.config, modules/artic.nf, workflows/articNcovNanopore.nf
These changes will allow medaka to run properly. Previously it would fail with our pipeline as I modified the inputs for the final QC. They now all match and will be run through properly
Needs a bit more validation before being merged in
=> update medaka workflow to run ncov-tools and not fail

bin/upload.py, conf/conda.config, modules/nml.nf, workflows/articNcovNanopore.nf
Adds process to upload data when running the pipeline with medaka
- Split upload process from uploadIRIDA to uploadIRIDA and uploadMedaka
- Adjusted the config file to match this for the environment
=> Add process to upload medaka output to IRIDA

bin/negative_control_fixes.py
- barcode added to the initial columns
=> Change CSV output order

bin/qc.py
- Output final QC column "pangoLEARN_version" changed just to "version"
=> Update QC.py for pangolin 4.0 output

extra_data/config.yaml
Change pangolin analysis mode to "fast" to match what is stored in the database
=> Change pangolin analysis mode in ncov-tools

bin/negative_control_fixes.py, bin/qc.py, conf/coguk/nml.config, environments/nanopore/environment.yml, modules/qc.nf, nextflow.config
Bumping artic environment to 1.2.3 as that updates medaka and longshot to deal with those issues.
- Note that longshot will still fail if there are about < 5 reads mapped so pre-filtering is a must or it will error
- Could add a pre-filter mapping step
- Could run the dehost pipeline with 5 min reads before
=> Artic env bump and QC Adjustments

bin/correct_n.py, bin/irida_fast5.py, bin/irida_upload_csv_generator.py, bin/negative_control_fixes.py, bin/qc.py
Adding better function definitions to the written python code to make it more readable
=> Quick pycode organization adjustments

CHANGELOG.md, README.md, bin/qc.py, nextflow.config
Integer only sample names were not being correctly parsed out of the nextclade results for frameshift comparison. This small update fixes this issue
=> Bugfix: int string comparison for nextclade
