phac-nml/ncov2019-artic-nf

- bin/irida_samples.py
- extra_data/config.yaml
- modules/help.nf
- modules/nml.nf
- workflows/articNcovNanopore.nf
Changes:
- csv parsing for sample info changed to tsv
- updates to help statements to reflect changes
- More specific file transfer to `./ncovtools/run` directory for ncovtools process
Still needs to be addressed:
- ~~what to do with ncovtools when `--irida` is not used as making the config won't find the metadata if `--irida` is not specified~~ --> Done
- May need to find a better way to use/create irida channel for when its not used and ncov tools is
> Add metadata to ncovtools

- bin/qc.py
- main.nf
* Update qc.py to reflect changed standards
* Filter out Illumina Undetermined_S0
* Make sure to negate the matcher
> Qc update (#56)

- workflows/articNcovNanopore.nf
- Stops empty fastq files from mucking up nanopolish and causing errors
- These files drop off of the face of the earth though
> Stop Error when fastq file is empty

- nextflow.config
Adding the nml conda dir to nextflow.config for the moment as remembering to re-specify it each time is annoying (and the pipeline will fail due to file paths being too long otherwise)
> Add conda dir to nextflow.config

- main.nf
- modules/nml.nf
- workflows/articNcovNanopore.nf
Keep track of samples that don't have enough reads or are filtered out based on read size and output them.
Read number filter can be changed in nanopore.conf
Output file names can change if needed, although I am not sure how we will push these to Irida based on how the qc csv table is generated
> Read size and read number filters

- bin/run_ncovtools.sh
- extra_data/config.yaml
- modules/nml.nf
Location of snakefile changed from `qc/` to `workflow/` so this update reflects that
Also changed completeness threshold back down to 0.75 for some of the poorer runs so that we don't fail on Augur with only one sequence (as likely to anyway)
> Change ncov-tools commands to reflect ncov-tools changes

- bin/qc.py
Some spots where the pools overlapped had variants showing up twice in the qc output.
Check added for this so only 1 will be reported
> Removal of double variants in csv output

- README.md
- environments/nanopore/environment.yml
- modules/artic.nf
Were updating the artic fieldinformatics module and environment to the latest version to get all of the new changes and fixes.
This version does not seem to like the way that our schemes are named and as such, the environment generated has to have the specific lines modified for it to work correctly at the moment
> Update artic to v1.2.1

- bin/upload.py
Issue with upload.py comparing what is on IRIDA to the incoming data where if the sample existed in IRIDA and didn't have the column it would crash out
> Small bugfix to upload.py

- bin/run_ncovtools.sh
Samples tagged as `neg`  were not being recognized as negative controls, this change will make it so that they are
> Add neg to look for negative samples list creation on ncov-tools

- conf/base.config
- main.nf
- modules/artic.nf
- modules/help.nf
- workflows/articNcovNanopore.nf
With external data, we need a flat workflow for nanopore data. The current implementation does not support this so a separate workflow was established
- Added `--flat` parameter to access the workflow (must be passed with `--medaka`)
- New "sequenceAnalysisMedakaFlat" workflow
> Add flat fastq workflow for medaka

- modules/artic.nf
- modules/nml.nf
- workflows/articNcovNanopore.nf
- Added tool versions outputs for processes that actually change/create data or upload it to IRIDA. Based on [nf-core adding modules](https://nf-co.re/developers/adding_modules)
- So ncov-tools, artic parts, n correction, snp-dists, etc.
- Not on the renaming, upload generator, or qc script
- Tool output is a final file called `process_versions.yml`
> Output tool versions on specific processes

- bin/run_ncovtools.sh
- Added move command to ncov-tools bash script to get the amplicon coverage table
> Move amplicon table to be detected

- conf/coguk/nml.config
- conf/resources.config
- modules/artic.nf
- modules/nml.nf
- ncovtools label removed
- mediumcpu label added instead
- ncovtools and medaka processes changed to mediumcpu
- Labels changed as it seemed medaka was having issues with the high amount of resources given to it
> Modify Medaka Resources 

- bin/negative_control_fixes.py
- bin/qc.py
- conf/coguk/nml.config
- main.nf
- modules/artic.nf
- modules/nml.nf
- modules/qc.nf
- workflows/articNcovNanopore.nf
- samples that fail the read coun and size selection filters will now be found in the nml.qc.csv file
- The previous tracking txt files are now tsv files with the data in them and if a samplesheet is given, the file contains the samplesheet info
- samples_failing_no_input_reads.tsv
- samples_failing_read_size_filter.tsv
- Adds environment variable for OpenBLAS threads to fix issues with the nml config spawning too many
- articNcovNanopore workflow now takes both the `fastq dirs` and the `bad fastq dirs` as input
- Setting the samplesheet channel is now done in the articNcovNanopore workflow instead of the sub workflows
- failing read count now specifically in the pipeline instead of in main
> Track failed samples in final qc.csv output

- environments/ncovtools.yml
- nextflow.config
- Fixed ncov-tools env to work with pangolin 4
- Was previously just updated manually to work for pangolin 4, now the env in this repo matches that in ncov-tools
- Add the `conda.useMamba` option for conda env creation
> Small conda environment updates

- bin/irida_fast5.py
- bin/irida_upload_csv_generator.py
Issue with samplesheets that just had integer IDs not running through the CSV generation step.
Forcing the sample column to be a string looks to fix it
> Force string column type for sample in IRIDA CSV Gen

- extra_data/config.yaml
Changing ncov-tools to run pangolin in accurate (usher) mode to try to assign more lineages
> Change ncov-tools to pangolin accurate

- .github/scripts/test_nml_nanopore_medaka.sh
- .github/scripts/test_nml_nanopore_medaka_flat.sh
- .github/scripts/test_nml_nanopore_nanopolish.sh
- conf/conda.config
- environments/extras.yml
- modules/artic.nf
- nextflow.config
BCFTools in the artic medaka pipeline fails semi-frequently due to how masking is performed. This update changes the logic to attempt the artic pipeline 3 times and if it fails all 3 times, the error is ignored and the sample skipped
Along with this, internally, a process has been written to pull out these failed samples after the run is done. I am not sure if there is a way to pull out failing samples in the pipeline itself or I would do it that way
- Ignore errors in ONLY medaka artic pipeline step
- Pin BCFTools to v1.15.1 in extras environment
- Added a mamba profile to separate mamba from conda
> Update logic for artic medaka pipeline

- bin/qc.py
Integer only names were failing qc.py due to a regex step. Adjusted that step to just force the input as a string
At some point the qc.py script should be revisited to make some improvements to the code but for now this should fix the issue
> Fix integer only names failing qc.py

- README.md
- conf/nanopore.config
- environments/nanopore/environment.yml
- nextflow.config
The artic tool was updated on August 22nd, 2023 and has a lot of bumped up tool versions, specifically medaka which now requests >1.8
Note that artic update has not gotten into bioconda yet - https://anaconda.org/bioconda/artic
---------------
Works!
Tested with a dataset and medaka v1.11.3 and output matched current so biggest difference is the ability to use newer models
> Update nanopore env to artic 1.2.4 released Aug22

- CHANGELOG.md
- README.md
- conf/base.config
- conf/nml.config
Revert back to internally ignoring errors when artic MinION fails due to the bcftools issue
> Adjust internal retry strategy for artic MinION
